version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: flask-postgres
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: